language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly


before_script:
- rustup component add rustfmt
- rustup component add clippy

script:
- cargo build
- cargo clippy --all-targets --all-features -- -D warnings
- cargo test
- cargo fmt --all -- --check