[package]
name = "battle-net-oauth"
version = "0.1.0"
authors = ["Shempignon <nicolas@pointndots.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9"
serde = "1.0"
rayon = "1.0"